1 ab photogram ajax
aborov/photogram-ajax pull request #1
Opened 2024-07-10 14:01 UTC by aborov

2024-07-10 14:38 UTC, aizatibraimova commented on app/controllers/comments_controller.rb
Great job of ensuring controllers respond to JavaScript request.

2024-07-10 14:42 UTC, jniewiel approved these changes
Great job overall with adding Ajax CRUD to all of your comments, likes, and follow requests!

2024-07-10 14:42 UTC, jniewiel commented on app/views/follow_requests/create.js.erb
> +});
Nice job with creating new comments! If you want to keep it all uniform between all of your CRUDs, you can make a new var form and also use "replaceWith" for your create and destroy JS files.

2024-07-10 14:42 UTC, jniewiel commented on app/views/comments/destroy.js.erb
> +});
Nice job with making deleted comments fade out!

2024-07-10 15:29 UTC, aizatibraimova approved these changes

2024-07-10 18:24 UTC, ahuynh3a commented on app/controllers/comments_controller.rb
> +
Remove necessary white space

2024-07-10 18:24 UTC, ahuynh3a commented on app/controllers/follow_requests_controller.rb
> +    @recipient = User.find(params[:follow_request][:recipient_id])
nitpik: remove any unnecessary white space

2024-07-10 18:24 UTC, ahuynh3a commented on app/controllers/follow_requests_controller.rb
> +
remove white space

2024-07-10 18:24 UTC, ahuynh3a commented on app/views/comments/_comment.html.erb
> +        <%= link_to comment,
remove white space

2024-07-10 18:24 UTC, ahuynh3a commented on app/views/comments/_form.html.erb
> +  <%= form_with(model: comment, local: false)  do |form| %>
great job being mindful of when to use 'local:false' and 'remote: true"

2024-07-10 18:24 UTC, ahuynh3a commented on app/views/comments/_form.html.erb
> +      <%= form.text_area :body, class: "form-control", id: "comment_body" %>
this comment_body id is not necessary as it already exists when you inspect the form on the DOM!

2024-07-10 18:24 UTC, ahuynh3a commented on app/views/comments/_form.html.erb
> +<li id="<%= dom_id(comment.photo) %>_<%= dom_id(comment) %>_form" class="list-group-item">
great job updating this unique id appropriately!

2024-07-10 18:24 UTC, ahuynh3a commented on app/views/photos/_photo.html.erb
> +
remove any unnecessary white space

2024-07-10 18:24 UTC, ahuynh3a commented on app/views/photos/_likes.html.erb
> +      <%= link_to like,
remove white space

2024-07-10 19:28 UTC, ahuynh3a requested changes
Hi Aleksei! You are off to a great start, please making the changes accordingly and I can review it again! Let me know if you have questions or need an explanation!

2024-07-10 19:28 UTC, ahuynh3a commented on app/javascript/follow_requests.js
I say delete this file and create a create.js.erb and destroy.js.erb for follow requests!

2024-07-10 19:28 UTC, ahuynh3a commented on app/views/follow_requests/_follow_unfollow.html.erb
>  <% unless sender == recipient %>
you can create a <div> tag and include the sender_id and recipient_id so that you can grab the current state of the follow/unfollow button in your js.erb files

2024-07-10 19:28 UTC, ahuynh3a commented on app/views/follow_requests/_form.html.erb
can you undo everything you deleted in this form?

2024-07-10 19:28 UTC, ahuynh3a commented on app/views/follow_requests/create.js.erb
> +document.querySelectorAll('.follow-container[data-user-id="<%= @recipient.id %>"]').forEach(function(container) {
This template should follow the convention you learned in the lesson. Start by grabbing the unique id you created in the _follow_unfollow.html.erb and then using .replaceWith "follow_requests/follow_unfollow" template

2024-07-11 19:35 UTC, ahuynh3a approved these changes
Thank you for making the changes Aleksei!!

2024-07-15 20:16 UTC, merged